version: '2'

volumes:
  mysql-data: {}
  redis-data: {}
  bundle-data: {}

services:
  project:
    build: .
    env_file:
      - .env
    # command: bundle exec rails s -p 3000 -b 0.0.0.0
    command: bin/docker-start
    volumes:
      - .:/mnt/diploma
      - bundle-data:/mnt/bundle
      # - .:/usr/app/diploma
      # - bundle-data:/usr/app/bundle
    ports:
      - 3000:3000
    links:
      - db
      - redis:redis

  db:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3316:3306
    command: ['mysqld', '--character-set-server=utf8']

  redis:
    image: redis
    ports:
      - 6380:6379
    volumes:
      - redis-data:/data
      